version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: juridiq-postgres
    restart: always
    environment:
      POSTGRES_DB: juridiq
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  postgres_data: